[project]
name = "tmp-seccon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pwntools>=4.14.1",
]

[tool.ruff]
# allow star imports for pwntools
ignore = [
    "F403",
    "F405"
]
